import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import "./globals.css";

import LoadingWrapper from "@/components/LoadingWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <SessionProvider>
          {/* <main>{children}</main> */}
          <LoadingWrapper>{children}</LoadingWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
